#!/bin/bash
# By Valerio G. Aimale

# Where we get the paths from
dirn=$(dirname "$0")
#echo $dirn

bundle=$(cd "$dirn/../../" && pwd)
bundle_contents="$bundle"/Contents
bundle_res="$bundle_contents"/Resources
bundle_lib="$bundle_res"/lib
bundle_bin="$bundle_res"/bin
bundle_sbin="$bundle_res"/sbin
bundle_data="$bundle_res"/share
bundle_etc="$bundle_res"/etc

PATH=${bundle_bin}:${bundle_sbin}:${PATH}

${bundle_bin}/fc-cache

exec "$bundle_res/bin/inkscape" $@ &>/dev/null

